language: python
python:
  - "3.8"
dist: bionic     # https://docs.travis-ci.com/user/languages/python/#python-37-and-higher
install:
  - travis_retry pip install -U -r doc/requirements.txt
  - travis_retry pip install -U -r test/requirements.txt
  - travis_retry pip install coveralls
  - travis_retry pip install -e .
script:
  - py.test --cov=pymapadmin
  - mypy pymapadmin test
  - flake8 pymapadmin test
after_success:
  - coveralls
  - make -C doc html
branches:
  only:
    - master
    - /^\d+\.\d+.*$/  # version tags
deploy:
  - provider: pages:git
    local_dir: doc/build/html
    on:
      tags: true
    edge: true
  - provider: pypi
    distributions: sdist bdist_wheel
    skip_existing: true
    on:
      tags: true
    edge: true
