# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: pymapadmin/grpc/admin.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import pymapadmin.grpc.admin_pb2


class AdminBase(abc.ABC):

    @abc.abstractmethod
    async def Ping(self, stream: 'grpclib.server.Stream[pymapadmin.grpc.admin_pb2.PingRequest, pymapadmin.grpc.admin_pb2.PingResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Append(self, stream: 'grpclib.server.Stream[pymapadmin.grpc.admin_pb2.AppendRequest, pymapadmin.grpc.admin_pb2.AppendResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/admin.Admin/Ping': grpclib.const.Handler(
                self.Ping,
                grpclib.const.Cardinality.UNARY_UNARY,
                pymapadmin.grpc.admin_pb2.PingRequest,
                pymapadmin.grpc.admin_pb2.PingResponse,
            ),
            '/admin.Admin/Append': grpclib.const.Handler(
                self.Append,
                grpclib.const.Cardinality.UNARY_UNARY,
                pymapadmin.grpc.admin_pb2.AppendRequest,
                pymapadmin.grpc.admin_pb2.AppendResponse,
            ),
        }


class AdminStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Ping = grpclib.client.UnaryUnaryMethod(
            channel,
            '/admin.Admin/Ping',
            pymapadmin.grpc.admin_pb2.PingRequest,
            pymapadmin.grpc.admin_pb2.PingResponse,
        )
        self.Append = grpclib.client.UnaryUnaryMethod(
            channel,
            '/admin.Admin/Append',
            pymapadmin.grpc.admin_pb2.AppendRequest,
            pymapadmin.grpc.admin_pb2.AppendResponse,
        )
